name: collect-github-data

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out repo
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Create auth.json
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "{\"github_personal_token\": \"$GITHUB_ACCESS_TOKEN\"}" > auth.json

      - name: Fetch data
        run: |
          # Scrape dependents
          github-to-sqlite scrape-dependents github.db pydata/xarray -v
          # Fetch pull-requests
          github-to-sqlite pull-requests github.db pydata/xarray
          # Fetch issues
          github-to-sqlite issues github.db pydata/xarray
          sqlite-utils tables --counts github.db
          # Delete email addresses from raw_authors
          sqlite-utils github.db "update raw_authors set email = ''"
          # Fetch emojis
          github-to-sqlite emojis github.db --fetch
          # Rebuild FTS tables
          sqlite-utils rebuild-fts github.db
          # Populate _analyze_tables_ table
          sqlite-utils analyze-tables github.db --save
